name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore ./visualizer_demo/visualizer_demo.csproj

    - name: Build
      run: dotnet build ./visualizer_demo/visualizer_demo.csproj -c Release --no-restore

    - name: Publish
      run: dotnet publish ./visualizer_demo/visualizer_demo.csproj -c Release -o ./publish

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-build
        path: ./publish
        retention-days: 7
